# Generated by Django 4.0.5 on 2022-07-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_tags_contact_birthday_contact_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SomeTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Some tag for your contact', max_length=200, verbose_name='Tag')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='tag_by_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contacts.sometag'),
        ),
    ]
