# Generated by Django 4.0.5 on 2022-07-15 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_tags_contact_birthday_contact_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailforcontact',
            name='detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.contact'),
        ),
    ]
