# Generated by Django 4.0.5 on 2022-07-23 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_sometag_contact_tag_by_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tag_by_many_to_many',
            field=models.ManyToManyField(related_name='tag_by_many_to_many', to='contacts.sometag'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='tag_by_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_by_foreign_key', to='contacts.sometag'),
        ),
    ]
