# Generated by Django 4.0.5 on 2022-07-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_tag_by_many_to_many_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.CharField(choices=[('family', '#family'), ('friend', '#friend'), ('work', '#work')], default='work', help_text='Tags dor you Contact', max_length=100, verbose_name='Tags'),
        ),
    ]
