# Generated by Django 4.0.5 on 2022-07-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='tags',
            field=models.CharField(blank=True, choices=[('family', '#family'), ('friend', '#friend'), ('work', '#work')], default='work', help_text='Tags dor you Contact', max_length=100, verbose_name='Tags'),
        ),
    ]
