# Generated by Django 4.0.5 on 2022-07-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_contact_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='detailforcontact',
            name='contact_type',
            field=models.CharField(blank=True, choices=[('APN', 'Phone number'), ('LinIn', 'Linkedin'), ('TG', 'Telegram'), ('EMAIL', 'Email')], default='LinIn', help_text='Add details about you Contact', max_length=100, verbose_name='Details'),
        ),
    ]
