# Generated by Django 4.0.5 on 2022-07-27 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_remove_contact_tag_by_foreign_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='tag_by_foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tag_by_foreign_key', to='contacts.sometag'),
        ),
    ]
