# Generated by Django 4.0.5 on 2022-07-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_tag_by_foreign_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.PositiveIntegerField(default=380, help_text='Phone number must start "380"', verbose_name='Phone Number'),
        ),
    ]
